export const NEW_CONTAINER_REQUEST = 'NEW_CONTAINER_REQUEST'
export const NEW_CONTAINER_SUCCESS = 'NEW_CONTAINER_SUCCESS'
export const NEW_CONTAINER_RESET = 'NEW_CONTAINER_RESET'
export const NEW_CONTAINER_FAIL = 'NEW_CONTAINER_FAIL'

export const ALL_CONTAINER_REQUEST = 'ALL_CONTAINER_REQUEST'
export const ALL_CONTAINER_SUCCESS = 'ALL_CONTAINER_SUCCESS'
export const ALL_CONTAINER_FAIL = 'ALL_CONTAINER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'